version: '3.8'

services:
  backend:
    build: ./beslenme_backend
    ports:
      - '8080:8080'
    depends_on:
      - db
  frontend:
    build: ./beslenme_frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beslenme_db
    ports:
      - '5432:5432'
