version: '3.9'
services:
  web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/web:/app
    container_name: web-1
    restart: always
    command: ['trunk', 'serve', '--address', '0.0.0.0', '--port', '8080']
