version: '3.8'
services:
  web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/web:/app:rw,delegated
  # web_app:
  #   build: ./frontend/web_app
  #   ports:
  #     - '8000:80'
  #   depends_on:
  #     - nutrition_service
  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - '6379:6379'
