version: '3'
services:
  nutrition_service:
    build: ./backend/nutrition_service
    ports:
      - '8081:8081'
    depends_on:
      - redis
  web_app:
    build: ./frontend/web_app
    ports:
      - '8000:80'
    depends_on:
      - nutrition_service
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
