apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nutrition-service
  template:
    metadata:
      labels:
        app: nutrition-service
    spec:
      containers:
        - name: nutrition-service
          image: your-dockerhub-username/nutrition_service:latest
          ports:
            - containerPort: 8081
