[package]
name="web_app"
version="0.1.0"
edition="2021"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"]}
reqwasm = "0.5"
stylist = "0.13"
