[build]
output = "dist"
watcher_ignore = [
    "dist/*",       # trunk'ın kendi build çıktıları
    "target/*",     # Rust'ın derleme çıktıları
    ".git/*",       # Git dosyaları
    "Dockerfile",   # Docker dosyaları
    "docker-compose.yml" # Compose dosyaları
]

[scss]
input = "static/styles/_globals.scss"
output = "dist/_globals.css"

[[build.hook]]
command = "sass"
args = ["static/styles:dist/styles", "--no-source-map", "--style=compressed"]
