[build]
# cargo trunk ya da trunk serve ile proje başlatıldığında oluşturulacak klasör ve dosyaların kaydedileceği dizin
output = "dist"
watcher_ignore = [
    "dist/*",       # trunk'ın kendi build çıktıları
    "target/*",     # Rust'ın derleme çıktıları
    ".git/*",       # Git dosyaları
    "Dockerfile",   # Docker dosyaları
    "docker-compose.yml" # Compose dosyaları
]

# trunk serve komutunun 127.0.0.1 adresinde ve 3001 portunda çalışmasını sağlıyoruz
[serve]
addresses = ["127.0.0.1"]
port = 3001

# [[copy]]
# source = "static"
# dest = "."