[package]
name = "nutrition_service"
version = "0.2.0"
edition = "2021"

[dependencies]
# Dokümanda belirtildiği gibi Sheets API, Serde ve OAuth kütüphanesi
google-sheets4 = "6.0.0"
serde = "1"
serde_json = "1"
yup-oauth2 = "11.0"

# Dokümanda kullanılan Hyper, Rustls, Hyper Util
hyper = { version = "1.5.2", features = ["client", "http1"] }
hyper-rustls = "0.27"
hyper-util = "0.1"

# Projenizin geri kalan bağımlılıkları
axum = "0.7"
tokio = { version = "1.42", features = ["macros", "io-util", "rt", "rt-multi-thread", "fs"] }
