[package]
name = "nutrition_service"
version = "0.2.0"
edition = "2021"

[dependencies]
# Http Routing
axum = "0.7.9"

# Asenkron
tokio = { version = "1.32", features = ["macros", "rt-multi-thread"] }

# Veriler to JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Middleware & logging
tower = "0.5"
tower-http = { version = "0.6", features = ["trace"] }

# Diesel gibi rust ile sql sorguları yönetimini büyük proje olmadığı için tercih etmedik.
# Rusqlite gibi sqlx gibi manuelsql yöntemi yetersiz kalabileceği ve async/await eklentilerini de kullanabilmek için sqlx tercih edilmiştir.
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "macros", "sqlite"] }

once_cell = "1.17"
# .env dosyalarından değer okumak için
dotenvy = "0.15"