[package]
name = "nutrition_service"
version = "0.2.0"
edition = "2021"

[dependencies]
# Dokümanda belirtildiği gibi Sheets API, Serde ve OAuth kütüphanesi
google-sheets4 = "6.0.0"
serde = "1.0"
serde_json = "1"
yup-oauth2 = "11.0"

hyper = { version = "1.5.2", features = ["full"] } # Hyper'ı Axum ile uyumlu versiyona güncelledik
hyper-rustls = "0.27"
hyper-util = { version = "0.1.10", features = ["client", "client-legacy", "http1"] }

# Eksik bağımlılıkları ekleyin
tower = "0.4"
tower-http = { version = "0.6.2", features = ["trace"] }

# Projenizin geri kalan bağımlılıkları
axum = "0.7"
tokio = { version = "1.42", features = ["macros", "io-util", "rt", "rt-multi-thread", "fs"] }
