[package]
name = "mobile_app"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.6", features = ["desktop", "mobile"] }
dioxus-desktop = "0.5.6"
serde = { version = "1.0", features = ["derive"]}
reqwest = "0.12.9"