apiVersion: apps/v1
kind: Deployment
metadata:
  name: besin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: besin-backend
  template:
    metadata:
      labels:
        app: besin-backend
    spec:
      containers:
        - name: besin-backend
          image: your-registry/besin-backend:latest
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: 'sqlite://data.db'
            - name: REDIS_URL
              value: 'redis://besin-redis:6379'
